# Generated by Django 4.2.5 on 2023-10-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='discount_type',
            field=models.IntegerField(choices=[(1, 'percent'), (2, 'amount')]),
        ),
    ]
